import { createBrowserRouter } from "react-router";
import {
  ArticleDetailPage,
  ArticlesPage,
  CertificateVerifyPage,
  CompanyProfilePage,
  ContactPage,
  HomePage,
  NotFoundPage,
  PrivacyPolicyPage,
  PublicLayoutPage,
  ServiceLandingPage,
  ServicesPage,
  ShopPage,
} from "../pages/public";
import {
  ForgotPasswordPage,
  LoginPage,
  RegisterPage,
  ResetPasswordPage,
} from "../pages/auth";
import {
  AboutPage,
  ActivitiesPage,
  BenefitsPage,
  BannersPage,
  CmsArticlesPage,
  CmsCompanyProfilePage,
  CmsDashboardPage,
  CmsLayoutPage,
  CmsLoginPage,
  CmsPrivacyPolicyPage,
  CmsProtectedPage,
  FinalCtaPage,
  GlobalSettingsPage,
  HeroPage,
  MediaLibraryPage,
  NavigationPage,
  ProductsPage,
  PromoPage,
  ServiceDetailPage,
  ServicesSectionPage,
  ShopManagementPage,
  TestimonialsPage,
  VisiMisiPage,
} from "../pages/cms";

export const router = createBrowserRouter([
  {
    path: "/",
    Component: PublicLayoutPage,
    children: [
      { index: true, Component: HomePage },
      { path: "company-profile", Component: CompanyProfilePage },
      { path: "services", Component: ServicesPage },
      { path: "services/:slug", Component: ServiceLandingPage },
      { path: "contact", Component: ContactPage },
      { path: "shop", Component: ShopPage },
      { path: "articles", Component: ArticlesPage },
      { path: "articles/:id", Component: ArticleDetailPage },
      { path: "certificate/verify", Component: CertificateVerifyPage },
      { path: "privacy-policy", Component: PrivacyPolicyPage },
      { path: "login", Component: LoginPage },
      { path: "register", Component: RegisterPage },
      { path: "forgot-password", Component: ForgotPasswordPage },
      { path: "reset-password/:token", Component: ResetPasswordPage },
      { path: "*", Component: NotFoundPage },
    ],
  },
  {
    path: "/cms/login",
    Component: CmsLoginPage,
  },
  {
    path: "/cms",
    Component: CmsProtectedPage,
    children: [
      {
        Component: CmsLayoutPage,
        children: [
          { index: true, Component: CmsDashboardPage },
          { path: "global", Component: GlobalSettingsPage },
          { path: "navigation", Component: NavigationPage },
          { path: "landing/hero", Component: HeroPage },
          { path: "landing/about", Component: AboutPage },
          { path: "landing/services", Component: ServicesSectionPage },
          { path: "landing/promo", Component: PromoPage },
          { path: "landing/products", Component: ProductsPage },
          { path: "landing/testimonials", Component: TestimonialsPage },
          { path: "landing/benefits", Component: BenefitsPage },
          { path: "landing/activities", Component: ActivitiesPage },
          { path: "landing/articles", Component: CmsArticlesPage },
          { path: "landing/visi-misi", Component: VisiMisiPage },
          { path: "landing/banners", Component: BannersPage },
          { path: "landing/final-cta", Component: FinalCtaPage },
          { path: "company", Component: CmsCompanyProfilePage },
          { path: "layanan/:slug", Component: ServiceDetailPage },
          { path: "shop", Component: ShopManagementPage },
          { path: "privacy", Component: CmsPrivacyPolicyPage },
          { path: "media", Component: MediaLibraryPage },
        ],
      },
    ],
  },
]);
