import { CoreQuestionCatalogEntry } from './core-scoring.types';

const yesNoOptions = [
  { label: 'Ya', value: 'Y' },
  { label: 'Tidak', value: 'N' },
];

const likertOptions = [
  { label: 'Sangat Setuju', value: '10' },
  { label: 'Setuju', value: '7' },
  { label: 'Ragu', value: '4' },
  { label: 'Tidak Setuju', value: '1' },
];

const tesBChoices = {
  q1: ['Merah', 'Hitam', 'Putih', 'Biru', 'Hijau'],
  q2: ['alat', 'nomor', 'warna', 'gambar', 'cerita'],
  q3: ['Pedas', 'Goreng', 'sate', 'Sayur', 'Berkuah'],
  q4: ['Niaga', 'Kerja', 'Istirahat', 'Belajar', 'Kopdar'],
  q5: ['AB', 'A', 'Tidak Tau', 'B', 'O'],
} as const;

const buildTesBOptions = (labels: readonly string[]) =>
  labels.map((label, index) => ({
    label: `${String.fromCharCode(65 + index)}. ${label}`,
    value: String.fromCharCode(65 + index),
  }));

const tesCQuestions = {
  sense_air: [
    'Saya lebih mudah memahami pelajaran dengan membaca, mendengar, melihat (segala cara)',
    'Saya cenderung mengingat materi pelajaran dengan aneka perlakuan',
    'saya lebih mudah mengingat sesuatu dari keunikan atau manfaatnya kepada saya',
    'Perhatian suka saya, bisa dipancing dengan segala cara, terutama jika diikutkan di kegiatan social',
    'Memahami sesuatu akan lebih mudah jika dilakukan diselingi dengan metode aneka hiburan',
  ],
  visual_kayu: [
    'Saya lebih mudah memahami pelajaran, setelah saya membaca kesimpulan terlebih dahulu',
    'Saya cenderung mengingat materi pelajaran dengan membayangkan dan menandai daripada mendengar',
    'Saya lebih mudah mengingat materi yang bergambar dan berwarna daripada yang tidak',
    'Saya lebih perhatian pada tulisan bertanda dan berwarna daripada dibacakan',
    'Memahami pelajaran lebih asik jika berisi nomor, grafik, diagram, gambar bahkan video',
  ],
  auditori_api: [
    'Saya lebih mudah memahami pelajara dengan cara diskusi atau kelompok',
    'Saya cenderung mengingat materi pelajaran dengan mendengar daripada membaca',
    'Saya lebih mudah mengingat materi yang diajarkan dengan cara dijelaskan daripada dituliskan',
    'Saya lebih perhatian pada bacaan orang lain daripada bacaan sendiri',
    'Memahami pelajaran lebih asik jika berisi nomor, grafik bahkan kesimpulan',
  ],
  reading_logam: [
    'Saya lebih mudah memahami pelajaran, setelah saya membaca lebih seksama',
    'Saya cenderung mengingat materi pelajaran dengan membaca lingkungan daripada menunggu',
    'Saya lebih mudah mengingat bacaan yang diberi nomor daripada yang tidak',
    'Saya lebih perhatian pada bacaan, daripada digambarkan atau dibacakan',
    'Memahami pelajaran lebih asik jika berisi nomor, grafik bahkan kesimpulan',
  ],
  kinestetik_tanah: [
    'Saya lebih mudah memahami pelajaran, setelah saya bermain terlebih dahulu',
    'Saya cenderung mengingat materi pelajaran dengan melihat daripada menunggu',
    'Saya lebih mudah mengingat hapalan dengan afirmasi contoh - materi dan sebagainya',
    'Saya lebih perhatian pada tulisan kekinian singkat daripada dengan tulisan panjang',
    'Memahami pelajaran lebih asik jika dijelaskan seperti berkelompok daripada sendirian',
  ],
} as const;

export const CORE_SCORING_QUESTION_CATALOG: CoreQuestionCatalogEntry[] = [
  {
    questionKey: 'tes_a.q1',
    text: 'Motivasi saya akan muncul jika saya terancam',
    stage: 'TES_A',
    slot: 1,
    answerType: 'boolean',
    displayOrder: 1,
    options: yesNoOptions,
  },
  {
    questionKey: 'tes_a.q2',
    text: 'Saya lebih menyukai evaluasi dengan sendiri',
    stage: 'TES_A',
    slot: 2,
    answerType: 'boolean',
    displayOrder: 2,
    options: yesNoOptions,
  },
  {
    questionKey: 'tes_a.q3',
    text: 'Saya suka berada di keramaian hingga berjam-jam',
    stage: 'TES_A',
    slot: 3,
    answerType: 'boolean',
    displayOrder: 3,
    options: yesNoOptions,
  },
  {
    questionKey: 'tes_a.q4',
    text: 'Gagasan sendiri jauh lebih asyik dikerjakan',
    stage: 'TES_A',
    slot: 4,
    answerType: 'boolean',
    displayOrder: 4,
    options: yesNoOptions,
  },
  {
    questionKey: 'tes_a.q5',
    text: 'Nyaman itu jika tidak harus melibatkan sekitar',
    stage: 'TES_A',
    slot: 5,
    answerType: 'boolean',
    displayOrder: 5,
    options: yesNoOptions,
  },
  {
    questionKey: 'tes_a.q6',
    text: 'Saya suka focus & konsentrasi dalam keramaian',
    stage: 'TES_A',
    slot: 6,
    answerType: 'boolean',
    displayOrder: 6,
    options: yesNoOptions,
  },
  {
    questionKey: 'tes_b.q1',
    text: 'Pilih warna favorit kamu',
    stage: 'TES_B',
    slot: 1,
    answerType: 'multiple_choice',
    displayOrder: 7,
    options: buildTesBOptions(tesBChoices.q1),
  },
  {
    questionKey: 'tes_b.q2',
    text: 'Dalam menganalisa, saya lebih cepat mengetahui dengan bantuan',
    stage: 'TES_B',
    slot: 2,
    answerType: 'multiple_choice',
    displayOrder: 8,
    options: buildTesBOptions(tesBChoices.q2),
  },
  {
    questionKey: 'tes_b.q3',
    text: 'Dari banyaknya jenis makanan, tapi saya lebih suka pada jenis masakan',
    stage: 'TES_B',
    slot: 3,
    answerType: 'multiple_choice',
    displayOrder: 9,
    options: buildTesBOptions(tesBChoices.q3),
  },
  {
    questionKey: 'tes_b.q4',
    text: 'Waktu, Sehat dan Sempat adalah anugrah. Selain untuk ibadah, akan saya manfaatkan untuk',
    stage: 'TES_B',
    slot: 4,
    answerType: 'multiple_choice',
    displayOrder: 10,
    options: buildTesBOptions(tesBChoices.q4),
  },
  {
    questionKey: 'tes_b.q5',
    text: 'Saya memiliki golongan darah',
    stage: 'TES_B',
    slot: 5,
    answerType: 'multiple_choice',
    displayOrder: 11,
    options: buildTesBOptions(tesBChoices.q5),
  },
  {
    questionKey: 'tes_c.sense_air.1',
    text: tesCQuestions.sense_air[0],
    stage: 'TES_C',
    slot: 1,
    answerType: 'likert',
    displayOrder: 12,
    groupKey: 'sense_air',
    groupElement: 'Air',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.sense_air.2',
    text: tesCQuestions.sense_air[1],
    stage: 'TES_C',
    slot: 2,
    answerType: 'likert',
    displayOrder: 13,
    groupKey: 'sense_air',
    groupElement: 'Air',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.sense_air.3',
    text: tesCQuestions.sense_air[2],
    stage: 'TES_C',
    slot: 3,
    answerType: 'likert',
    displayOrder: 14,
    groupKey: 'sense_air',
    groupElement: 'Air',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.sense_air.4',
    text: tesCQuestions.sense_air[3],
    stage: 'TES_C',
    slot: 4,
    answerType: 'likert',
    displayOrder: 15,
    groupKey: 'sense_air',
    groupElement: 'Air',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.sense_air.5',
    text: tesCQuestions.sense_air[4],
    stage: 'TES_C',
    slot: 5,
    answerType: 'likert',
    displayOrder: 16,
    groupKey: 'sense_air',
    groupElement: 'Air',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.visual_kayu.1',
    text: tesCQuestions.visual_kayu[0],
    stage: 'TES_C',
    slot: 1,
    answerType: 'likert',
    displayOrder: 17,
    groupKey: 'visual_kayu',
    groupElement: 'Kayu',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.visual_kayu.2',
    text: tesCQuestions.visual_kayu[1],
    stage: 'TES_C',
    slot: 2,
    answerType: 'likert',
    displayOrder: 18,
    groupKey: 'visual_kayu',
    groupElement: 'Kayu',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.visual_kayu.3',
    text: tesCQuestions.visual_kayu[2],
    stage: 'TES_C',
    slot: 3,
    answerType: 'likert',
    displayOrder: 19,
    groupKey: 'visual_kayu',
    groupElement: 'Kayu',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.visual_kayu.4',
    text: tesCQuestions.visual_kayu[3],
    stage: 'TES_C',
    slot: 4,
    answerType: 'likert',
    displayOrder: 20,
    groupKey: 'visual_kayu',
    groupElement: 'Kayu',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.visual_kayu.5',
    text: tesCQuestions.visual_kayu[4],
    stage: 'TES_C',
    slot: 5,
    answerType: 'likert',
    displayOrder: 21,
    groupKey: 'visual_kayu',
    groupElement: 'Kayu',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.auditori_api.1',
    text: tesCQuestions.auditori_api[0],
    stage: 'TES_C',
    slot: 1,
    answerType: 'likert',
    displayOrder: 22,
    groupKey: 'auditori_api',
    groupElement: 'Api',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.auditori_api.2',
    text: tesCQuestions.auditori_api[1],
    stage: 'TES_C',
    slot: 2,
    answerType: 'likert',
    displayOrder: 23,
    groupKey: 'auditori_api',
    groupElement: 'Api',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.auditori_api.3',
    text: tesCQuestions.auditori_api[2],
    stage: 'TES_C',
    slot: 3,
    answerType: 'likert',
    displayOrder: 24,
    groupKey: 'auditori_api',
    groupElement: 'Api',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.auditori_api.4',
    text: tesCQuestions.auditori_api[3],
    stage: 'TES_C',
    slot: 4,
    answerType: 'likert',
    displayOrder: 25,
    groupKey: 'auditori_api',
    groupElement: 'Api',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.auditori_api.5',
    text: tesCQuestions.auditori_api[4],
    stage: 'TES_C',
    slot: 5,
    answerType: 'likert',
    displayOrder: 26,
    groupKey: 'auditori_api',
    groupElement: 'Api',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.reading_logam.1',
    text: tesCQuestions.reading_logam[0],
    stage: 'TES_C',
    slot: 1,
    answerType: 'likert',
    displayOrder: 27,
    groupKey: 'reading_logam',
    groupElement: 'Logam',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.reading_logam.2',
    text: tesCQuestions.reading_logam[1],
    stage: 'TES_C',
    slot: 2,
    answerType: 'likert',
    displayOrder: 28,
    groupKey: 'reading_logam',
    groupElement: 'Logam',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.reading_logam.3',
    text: tesCQuestions.reading_logam[2],
    stage: 'TES_C',
    slot: 3,
    answerType: 'likert',
    displayOrder: 29,
    groupKey: 'reading_logam',
    groupElement: 'Logam',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.reading_logam.4',
    text: tesCQuestions.reading_logam[3],
    stage: 'TES_C',
    slot: 4,
    answerType: 'likert',
    displayOrder: 30,
    groupKey: 'reading_logam',
    groupElement: 'Logam',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.reading_logam.5',
    text: tesCQuestions.reading_logam[4],
    stage: 'TES_C',
    slot: 5,
    answerType: 'likert',
    displayOrder: 31,
    groupKey: 'reading_logam',
    groupElement: 'Logam',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.kinestetik_tanah.1',
    text: tesCQuestions.kinestetik_tanah[0],
    stage: 'TES_C',
    slot: 1,
    answerType: 'likert',
    displayOrder: 32,
    groupKey: 'kinestetik_tanah',
    groupElement: 'Tanah',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.kinestetik_tanah.2',
    text: tesCQuestions.kinestetik_tanah[1],
    stage: 'TES_C',
    slot: 2,
    answerType: 'likert',
    displayOrder: 33,
    groupKey: 'kinestetik_tanah',
    groupElement: 'Tanah',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.kinestetik_tanah.3',
    text: tesCQuestions.kinestetik_tanah[2],
    stage: 'TES_C',
    slot: 3,
    answerType: 'likert',
    displayOrder: 34,
    groupKey: 'kinestetik_tanah',
    groupElement: 'Tanah',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.kinestetik_tanah.4',
    text: tesCQuestions.kinestetik_tanah[3],
    stage: 'TES_C',
    slot: 4,
    answerType: 'likert',
    displayOrder: 35,
    groupKey: 'kinestetik_tanah',
    groupElement: 'Tanah',
    options: likertOptions,
  },
  {
    questionKey: 'tes_c.kinestetik_tanah.5',
    text: tesCQuestions.kinestetik_tanah[4],
    stage: 'TES_C',
    slot: 5,
    answerType: 'likert',
    displayOrder: 36,
    groupKey: 'kinestetik_tanah',
    groupElement: 'Tanah',
    options: likertOptions,
  },
];
