export { CMSLoginPage as CmsLoginPage } from "./CMSLoginPage";
export { CMSProtectedRoute as CmsProtectedPage } from "./CMSProtectedRoute";
export { CMSLayout as CmsLayoutPage } from "./CMSLayout";
export { CMSDashboard as CmsDashboardPage } from "./CMSDashboard";
export { GlobalSettingsPage } from "./GlobalSettingsPage";
export { HeroPage } from "./HeroPage";
export { AboutPage } from "./AboutPage";
export { ServicesSectionPage } from "./ServicesSectionPage";
export { PromoPage } from "./PromoPage";
export { ProductsPage } from "./ProductsPage";
export { TestimonialsPage } from "./TestimonialsPage";
export { BenefitsPage } from "./BenefitsPage";
export { ActivitiesPage } from "./ActivitiesPage";
export { CMSArticlesPage as CmsArticlesPage } from "./ArticlesPage";
export { VisiMisiPage } from "./VisiMisiPage";
export { BannersPage } from "./BannersPage";
export { FinalCTAPage as FinalCtaPage } from "./FinalCTAPage";
export { CMSCompanyProfilePage as CmsCompanyProfilePage } from "./CompanyProfilePage";
export { ServiceDetailPage } from "./ServiceDetailPage";
export { ShopManagementPage } from "./ShopManagementPage";
export { CMSPrivacyPolicyPage as CmsPrivacyPolicyPage } from "./PrivacyPolicyPage";
export { MediaLibraryPage } from "./MediaLibraryPage";
export { NavigationPage } from "./NavigationPage";
