export const DEFAULT_SITE_SETTINGS = {
  siteName: 'NEWME CLASS',
  siteTitle: 'NEWME CLASS',
  siteDescription: 'Kelas Peduli Talenta',
  email: 'newmeclass@gmail.com',
  phone: '0895.0267.1691',
  whatsapp: '6289502671691',
  instagram: '@newmeclass',
  website: '',
  address: 'Jl. Puskesmas I - Komp. Golden Seroja - A1',
  logoUrl: '',
  faviconUrl: '',
  primaryColor: '#FFD700',
  secondaryColor: '#1a1a1a',
  accentColor: '#2a2a2a',
  backgroundColor: '#1a1a1a',
  textColor: '#ffffff',
  seoKeywords: '',
  seoMetaDescription: '',
  googleAnalyticsId: '',
  facebookPixelId: '',
  maintenanceMode: false,
  maintenanceMessage: 'Kami sedang melakukan pemeliharaan sistem. Silakan kembali beberapa saat lagi.',
  allowRegistration: true,
  popupEnabled: true,
  requirePayment: true,
  paymentAmount: 100000,
  bankName: 'BCA',
  bankAccountNumber: '1234567890',
  bankAccountName: 'NEWME CLASS',
  paymentInstructions: '',
  boardOfDirectors: [],
  teamSupport: [],
  partners: [],
  companyTestimonials: [],
  clientBenefits: [],
  services: [],
  visiMisi: {
    visi: '',
    misi: '',
    subMisi: '',
  },
  kelasGaliBakat: {
    title: '',
    subtitle: '',
    description: '',
    purpose: '',
    phases: [],
    benefits: [],
    procedures: [],
  },
  devFeePercent: 5,
  devBankName: '',
  devBankAccount: '',
  devAccountName: '',
};

export const normalizeSiteSettings = (settings: any) => {
  const safeSettings = settings && typeof settings === 'object' ? settings : {};

  return {
    ...DEFAULT_SITE_SETTINGS,
    ...safeSettings,
    visiMisi: {
      ...DEFAULT_SITE_SETTINGS.visiMisi,
      ...(safeSettings.visiMisi && typeof safeSettings.visiMisi === 'object' ? safeSettings.visiMisi : {}),
    },
    kelasGaliBakat: {
      ...DEFAULT_SITE_SETTINGS.kelasGaliBakat,
      ...(safeSettings.kelasGaliBakat && typeof safeSettings.kelasGaliBakat === 'object' ? safeSettings.kelasGaliBakat : {}),
    },
    boardOfDirectors: Array.isArray(safeSettings.boardOfDirectors) ? safeSettings.boardOfDirectors : [],
    teamSupport: Array.isArray(safeSettings.teamSupport) ? safeSettings.teamSupport : [],
    partners: Array.isArray(safeSettings.partners) ? safeSettings.partners : [],
    companyTestimonials: Array.isArray(safeSettings.companyTestimonials) ? safeSettings.companyTestimonials : [],
    clientBenefits: Array.isArray(safeSettings.clientBenefits) ? safeSettings.clientBenefits : [],
    services: Array.isArray(safeSettings.services) ? safeSettings.services : [],
  };
};
